# https://docs.cypress.io/guides/continuous-integration/github-actions
name: Cypress Tests
on:
  push:
    branches: ["*"]
  pull_request:
    branches:
      - main

jobs:
  # Create and save build
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build project
        uses: cypress-io/github-action@v6
        env:
          BLOB_URL: ${{ secrets.BLOB_URL }}
        with:
          # Disable running of tests within install job
          runTests: false
          build: yarn run build

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          include-hidden-files: true
          path: .next

  e2e:
    runs-on: ubuntu-22.04
    needs: install

    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .next

      - name: Cypress run e2e tests
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          # Starts web server for E2E tests - replace with your own server invocation
          # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
          start: yarn start
          wait-on: "http://localhost:3000" # Waits for above
          # Records to Cypress Cloud
          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
          # record: true
          # parallel: true # Runs test in parallel using settings above
          browser: chrome

  component:
    runs-on: ubuntu-22.04
    needs: install

    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .next

      - name: Cypress run component tests
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          # Records to Cypress Cloud
          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
          # record: true
          #parallel: true # Runs test in parallel using settings above
          browser: chrome
          component: true
          # working-directory: examples/component-tests
          # spec: components/**/*cy.tsx
